# version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/tasks
      - JWT_SECRET=change-this-secret
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
